name: Generate Music from Natural Language Prompt (MusicGen)

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter music description (e.g., Peaceful bamboo chimes blended with stream)'
        required: true
        default: 'Peaceful bamboo chimes blended with a gentle mountain stream for sleep and calm'

jobs:
  musicgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Generate music with Hugging Face MusicGen
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          echo "Generating music for prompt: $PROMPT"
      
          curl -L -X POST "https://api-inference.huggingface.co/models/facebook/musicgen-melody" \
            -H "Authorization: Bearer $HF_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\": \"$PROMPT\"}" \
            --output output.wav
      
          # Check if file is really audio
          file output.wav
      
          if ! file output.wav | grep -q "RIFF (little-endian) data"; then
            echo "❌ Invalid audio received from Hugging Face."
            cat output.wav
            exit 1
          fi
      
          echo "✅ Audio received, converting to MP3"
          ffmpeg -y -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3



      - name: Upload generated audio files
        uses: actions/upload-artifact@v4
        with:
          name: musicgen_output
          path: |
            output.wav
            output.mp3
