name: Generate Music with Hugging Face MusicGen Space

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter your music prompt'
        required: true
        default: 'Peaceful bamboo chimes blended with a gentle mountain stream for sleep and calm'

jobs:
  generate-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq curl

      - name: Generate Music from Prompt (Hugging Face Space API)
        env:
          PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          echo "🎶 Prompt: $PROMPT"

          echo "📡 Sending request to Hugging Face MusicGen Space..."
          RESPONSE=$(curl -s -X POST https://fffiloni-musicgen.hf.space/api/predict/ \
            -H "Content-Type: application/json" \
            -d "{\"data\": [\"$PROMPT\"]}")

          echo "$RESPONSE" > response.json
          cat response.json

          AUDIO_PATH=$(jq -r '.data[1].name' response.json)

          if [[ "$AUDIO_PATH" == "null" || -z "$AUDIO_PATH" ]]; then
            echo "❌ Failed to get audio path. Full response:"
            cat response.json
            exit 1
          fi

          echo "🎧 Downloading audio: $AUDIO_PATH"
          curl -L "https://fffiloni-musicgen.hf.space/file=$AUDIO_PATH" --output output.wav

          echo "🎵 Converting WAV to MP3"
          ffmpeg -y -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: musicgen-audio
          path: |
            output.wav
            output.mp3
