name: Generate Music via MusicGen Transformer in GitHub Action

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter natural-language music prompt'
        required: true
        default: 'Peaceful bamboo chimes blended with a gentle mountain stream for sleep and calm'

jobs:
  generate-music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🧾
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip install transformers torch scipy

      - name: Generate music with MusicGen (manual model load)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          pip install transformers torchaudio scipy
          python3 gen_music.py



      - name: Transcode to MP3
        run: |
          ffmpeg -y -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3
          ls -lh output.*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: musicgen-clip-${{ github.run_id }}
          path: output.wav, output.mp3
