name: Generate Music via Hugging Face Space API (suno-musicgen)

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter a music prompt'
        required: true
        default: 'Peaceful bamboo chimes blended with a gentle mountain stream for sleep and calm'

jobs:
  generate-music:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg jq curl

      - name: Call Hugging Face Space API
        env:
          PROMPT: ${{ github.event.inputs.prompt }}
        run: |
          echo "📝 Prompt: $PROMPT"

          RESPONSE=$(curl -s -X POST https://lj1995-musicgen.hf.space/run/predict \
            -H "Content-Type: application/json" \
            -d "{\"data\": [\"$PROMPT\"]}")

          echo "$RESPONSE" > response.json
          cat response.json

          AUDIO_PATH=$(jq -r '.data[1].name' response.json)

          if [[ "$AUDIO_PATH" == "null" || -z "$AUDIO_PATH" ]]; then
            echo "❌ No audio generated. Response:"
            cat response.json
            exit 1
          fi

          echo "🎧 Downloading audio from $AUDIO_PATH"
          curl -L "https://lj1995-musicgen.hf.space/file=$AUDIO_PATH" -o output.wav

      - name: Convert WAV to MP3
        run: |
          ffmpeg -y -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3

      - name: Upload audio artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-music
          path: |
            output.wav
            output.mp3
