name: Generate Music with Hugging Face Space

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Enter your music prompt'
        required: true
        default: 'Peaceful bamboo chimes blended with a gentle mountain stream for sleep and calm'

jobs:
  generate-music:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq curl

      - name: Generate Music with Hugging Face Space
        env:
          PROMPT: ${{ github.event.inputs.prompt }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "🎶 Prompt: $PROMPT"

          echo "📡 Sending request to Hugging Face Space"
          RESPONSE=$(curl -s -X POST "https://fffiloni-musicgen.hf.space/run/predict" \
            -H "Authorization: Bearer $HF_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"data\": [\"$PROMPT\"]}")

          echo "$RESPONSE" > response.json
          cat response.json

          AUDIO_FILE=$(jq -r '.data[1].name' response.json)

          if [[ "$AUDIO_FILE" == "null" || -z "$AUDIO_FILE" ]]; then
            echo "❌ No audio file found in response"
            exit 1
          fi

          echo "🎧 Downloading audio: $AUDIO_FILE"
          curl -L "https://fffiloni-musicgen.hf.space/file=$AUDIO_FILE" --output output.wav

          echo "🎵 Converting to MP3"
          ffmpeg -y -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3

      - name: Upload audio files
        uses: actions/upload-artifact@v4
        with:
          name: generated-music
          path: |
            output.wav
            output.mp3
