name: Generate AI Music from Prompt

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Describe the music (e.g., "happy melody in C major")'
        required: true
        default: 'happy melody in C major'

jobs:
  generate-music:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y timidity
          pip install music21

      - name: Generate MIDI from prompt
        run: |
          python3 generate_music.py

        env:
          PROMPT: ${{ github.event.inputs.prompt }}

      - name: Convert MIDI to WAV (optional)
        run: |
          timidity output.mid -Ow -o output.wav
          ffmpeg -i output.wav -codec:a libmp3lame -qscale:a 2 output.mp3

      - name: Upload Music Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AI_Music_${{ github.run_id }}
          path: |
            output.mid
            output.mp3

