name: Upload - Not working

on:
  workflow_dispatch:

jobs:
  make_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        pip install -r requirements.txt || true  # Optional: install your other deps

    - name: Run video generation script
      run: |
        chmod +x scripts/make_video.sh
        bash scripts/make_video.sh

    - name: Upload to YouTube
      run: |
        python upload_to_youtube.py
      env:
        CLIENT_SECRET_FILE: client_secret.json
        VIDEO_FILE: 080425video10.mp4
        TITLE: "Relaxing Nature Video"
        DESCRIPTION: "Generated and uploaded via GitHub Actions"
        CATEGORY: "22"            # Category 22 = People & Blogs
        PRIVACY: "unlisted"       # or "public", "private"
